config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :posts do
    resources :comments
  end

  get "home/index"

  get "search" => "search#index"

  root to: "home#index"

  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord

    has_many :post_hash_tags
    has_many :posts, through: :post_hash_tags
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  validate :image_presence
  validates :description, presence: true

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

  has_many :post_hash_tags, dependent: :destroy
  has_many :hash_tags, through: :post_hash_tags, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_commit :create_hash_tags, on: :create

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map { |name| name.gsub("#", "") }
  end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord

    belongs_to :post
    belongs_to :hash_tag
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  validates_presence_of :username

  has_many :posts, dependent: :destroy

  has_one_attached :avatar

  validates :email, presence: true
  validates :username, presence: true

  #mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Comment has been created"
    else
      flash.now[:alert] = "Comment has not been created"
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post has been created"
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = "Post has not been created"
      render :new
    end
  end

  def show
    @comment = @post.comments.build
    @comments = @post.comments.order(created_at: :desc)
  end

  def index
    @posts = Post.order(created_at: :desc)
  end

  def destroy
    unless @post.user == current_user
      flash[:alert] = "You can only delete your own post."
      render :show
    else
      if @post.destroy
        flash[:notice] = "Post has been deleted."
        redirect_to user_path(current_user)
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController  
  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name: query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User has been updated"
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = "User has not been updated"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website, :bio, :email, :phone, :gender, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def persisted_comments(comments)
    comments.reject { |comment| comment.new_record? }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment-body">
  <%= link_to user.username, user_path(user), class: 'username' %>: <%= comment %>
</div>
<hr />

app/views/home/index.html.erb
<div class="posts-home">
  <% if @posts.any? %>
    <% @posts.each do |post| %>
      <section class="post">
      <div class="user">
        <div class="avatar">
          <%= link_to user_path(post.user) do %>
            <% if post.user.avatar.attached? %>
              <%= image_tag post.user.avatar %>
            <% else %>
              <%= image_tag src="https://www.tipsaludable.com/wp-content/uploads/2017/08/b1-8.jpg" %>
            <% end %>
          <% end %>
        </div>
        <%= link_to post.user.username, user_path(post.user), class: 'username' %>
      </div>
      <%= image_tag post.image, class: 'main-image' %> 
        <div class="description">
          <% post.description.to_s.split(' ').each do |word| %>
            <% if word.start_with?('#') %>
              <%= link_to word, search_path(query: word) %>
            <%else %>
              <%= word %>
            <%end %>
          <% end %>
        </div>
      </section>
    <% end %>
  <% else %>
    <%= render 'shared/message', message: "There are no posts to show.", key: "primary" %>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'shared/header' %>

    <%= render 'shared/alerts' %>

    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/new.html.erb
  <%= render 'shared/errors', object: @post, name: 'post' %>
  <%= form_for(@post, :html => {class: "form-upload", role: "form"}) do |f| %>
  
  <h1 class="h1 center-block">Create post</h1>
    <br>
    <div class="form-group">
      <%= f.text_field :description, id: "description" %>
    </div>
    <div class="form-group">
      <label class="btn btn-default btn-change-avatar center-block labelUploader">
        Upload new image
        <span style="display: none;">
          <%= f.file_field :image, id: "fileUploader"%>
        </span>
      </label>
    </div>
    <br>
    <div class="text-center">
      <%= f.submit 'Create post', class: 'btn btn-primary' %>
    </div>
  <% end %>

app/views/posts/show.html.erb
<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
      <div class="delete">
        <% if current_user == @post.user %>
          <%= link_to 'Remove', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
    <div class="description">
      <% @post.description.to_s.split(' ').each do |word| %>
        <% if word.start_with?('#') %>
          <%= link_to word, search_path(query: word) %>
        <%else %>
          <%= word %>
        <%end %>
      <% end %>
    </div>
    <hr>
    <div class='col-md-12 comments'>
      <% if @post.comments.any? %>
        <div id="messages">
          <% persisted_comments(@comments).each do |comment| %>
            <div class="comment-body">
              <%= link_to comment.user.username, user_path(comment.user), class: 'username' %>: <%= comment.body %>
            </div>
            <hr>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? %>
     <div class='col-md-12 comment'>
        <%= form_for [@post, @comment], remote: true, :html => {class: "form-horizontal", role: "form"} do |f| %>
          <input type="hidden" id="post_id" value=<%= "#{@post.id}" %>>
          <div class='form-group'>
            <div class='col-md-12'>
              <%= f.text_field :body, rows: 10, class: 'form-control', placeholder: 'Your comment' %>
            </div>
          </div>
          <div class='invisible'>
            <div class=''>
              <%= f.submit "Add Comment", class: 'add-comment-button' %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/search/index.html.erb
<div class="search-page">
  <% if @posts.exists? %>
    <%= render 'shared/message', message: "Top posts", key: "dark" %>
    <div class="user-images">
      <% @posts.each do |post|%>
        <div class="wrapper">
          <%=link_to post_path(post) do %>
            <%=image_tag post.image %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= render 'shared/message', message: "Ops! no matching posts.", key: "primary" %>
  <% end %>
</div>

app/views/shared/_alerts.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger col-md-offset-1">
    <div class="panel-heading">
      <h2 class="panel-title">
        <%= pluralize(object.errors.count, "error") %>
        prohibited this <%= name %> from being saved:
      </h2>
      <div class="panel-body">
        <ul>
          <% object.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container footer">
  <nav class="navbar d-flex">
    <ul>
      <li>ABOUT US</li>
      <li>SUPPORT</li>
      <li>PRESS</li>
      <li>API</li>
      <li>JOBS</li>
      <li>PRIVACY</li>
      <li>TERMS</li>
      <li>DIRECTORY</li>
      <li>PROFILES</li>
      <li>HASHTAGS</li>
      <li>LANGUAGE</li>
      </ul>
    <p> © 2019 INSTAGRAM </p>
  </nav>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light bg-light d-flex">
  <div class="container">
    <div class="logo">
      <a class="navbar-brand" href="/">
        <%= fa_stacked_icon "camera inverse", base: "circle"%>
          Instagram
      </a>
    </div>
    <div class="m-auto">
      <%= form_with url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
        <%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: '#search' %>
      <% end %>
      </div>
      <div class="user-section">
        <% if user_signed_in? %>
          <a><%= link_to "#{current_user.username}", user_path(current_user)%>
            <i class="fa fa-user"></i>
          </a>
          <a><%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
            <i class="fa fa-user-times"></i>
          </a>
        <% else %>
          <a><%= link_to "Sign in", new_user_session_path %>
            <i class="fa fa-sign-in"></i>
          </a>
          <a><%= link_to "Sign up", new_user_registration_path %>
            <i class="fa fa-user-plus"></i>
          </a>
        <% end %>
      </div>
  </div>
</nav>

app/views/shared/_message.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <div class="text-center alert alert-<%= key %>">
          <%= message %>
        </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/errors', object: @user, name: 'user' %>
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_for(@user, local: true, html: {class: "form-horizontal form-edit-user", role: "form"}) do |f| %>
        <div class="form-group row">
            <div class="col-sm-3 col-form-label">
              <% if @user.avatar.attached? %>
                <%= image_tag @user.avatar, class: 'avatar' %>
              <%end %>
            </div>
            <div class="col-sm-9">
            <p class="username"><%=@user.username %></p>
            </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
            <%= f.label :name, class: 'col-sm-3 col-form-label' %>
            <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :username, class: 'col-sm-3 col-form-label' %>
            <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :website, class: 'col-sm-3 col-form-label' %>
            <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
            <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :email, class: 'col-sm-3 col-form-label' %>
            <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
            <div class="col-sm-9">
            <%= f.text_field :phone, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
            <div class="col-sm-9">
            <%= f.text_field :gender, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-9">
            <%= f.submit "Edit", class: 'btn btn-primary' %>
            </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <% else %>
          <%= image_tag("image.jpg") %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <% if current_user == @user %>
        <a>
          <%= link_to "Edit profile", edit_user_path(@user), class: "edit-profile"%>
        </a>
        <a>
          <%= link_to "Create post", new_post_path(@user), class: "edit-profile"%>
        </a>
        <% end %>
      </div>
      <ul class="posts">
        <li><span><%= pluralize(@posts.count, "post") %></span></li>
        <li><span>195</span> followers</li>
        <li><span>345</span> following</li>
      </ul>
      <% if @user.name?%>
        <h2 class="name"><%= @user.name %></h2>
      <% end %>
      <% if @user.website?%>
        <h2 class="website"> <%= @user.website %></h2>
      <% end %>
    </div>
  </div>
</div>

<div class="user-tabs">
  <a class="tab active" href="">
    <i class="fa fa-th"></i>
    POSTS
  </a>
  <a class="tab" href="">
    <i class="fa fa-tv"></i>
    IGTV
  </a>
  <a class="tab" href="">
    <i class="fa fa-bookmark"></i>
    SAVED
  </a>
  <a class="tab" href="">
    <i class="fa fa-tag"></i>
    TAGGED
  </a>
</div>

<div class="user-images">
  <% if @posts.any? %>
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to post_path(post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <%= render 'shared/message', message: "There are no posts to show.", key: "primary" %>
  <% end %>
</div>